### PR TITLE
fixed applet jumping back to old location after tag switch

### LINKED ISSUE #545: seafile-applet switches screens
in the case that i put my seafile-applet to my second monitor and switch to a new tag (https://awesome.naquadah.org/doc/api/modules/awful.tag.html), virtual desktop, and back. The applet changes from screen 2 to screen 1(monitor 1).

### PR DESCRIPTION
**Pull request by vulder**
Closes #545.

### CODE REVIEW

File: src/ui/main-window.cpp [hunk 1]
```diff
@@ -125,6 +125,11 @@ bool MainWindow::event(QEvent *ev)
             writeSettings();
         }
     }
+
+    if (ev->type() == QEvent::Hide) {
+      writeSettings();
```
Comment (Chilledheart) [inline src/ui/main-window.cpp]: We indent 4 spaces in stead of 2.

Comment (vulder) [inline src/ui/main-window.cpp]: fixed

**Comment by Chilledheart** [comment]
LGTM
